query ListAllProducts @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  products {
    id
    name
    description
    price
  }
}

query MyPosts @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  posts(where: {userUid: {eq_expr: "auth.uid"}}) {
    id
    title
    content
    createdAt
  }
}

mutation CreatePost($title: String!, $content: String!) @auth(level: USER) {
  post_insert(data: {
    title: $title,
    content: $content,
    userUid_expr: "auth.uid",
    createdAt_expr: "request.time"
  })
}

query ListProductsByCategory($category: String!) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  products(where: {category: {eq: $category}}) {
    id
    name
    price
    description
  }
}